function [] = write_colorbar_limits(maplimits)

    % ***
    % This functions writes the min and max value of the topoplot 
    % in the upper right corner  

    % Get current colormap
    cset = colormap(gca);

    % Axis height and width
    ax = get(gca, 'Position');
    axis_height = ax(4);
    axis_width  = ax(3);

    % Fontsize
    fontsize = axis_height * 25;

    % Axis limits
    xL = xlim;
    yL = ylim;

    % Maplimits
    low_limit = sprintf('%.2f', maplimits(1));
    up_limit  = sprintf('%.2f', maplimits(2));

    % *** Upper limit number
    text( 0.99*xL(2), 0.99*yL(2), ...
        { ...
            ['\color[rgb]', sprintf('{%.4f, %.4f, %.4f}', cset(end, 1), cset(end, 2), cset(end, 3)), up_limit], ...
            ['\color[rgb]', sprintf('{%.4f, %.4f, %.4f}', cset(1, 1), cset(1, 2), cset(1, 3)), low_limit] ...
            }, ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', [.9 .9 .9], ...
        'Margin', 1, ...
        'FontSize', fontsize)    

    % % *** Upper limit number
    % text( 0.99*xL(2), 0.99*yL(2), ...
    %     { ...
    %       {sprintf('\color[rgb]{%d, %d, %d}%s', cset(end, 1), cset(end, 2), cset(end, 3), up_limit)} ...
    %       {sprintf('\color[rgb]{%d, %d, %d}%s', cset(1, 1), cset(1, 2), cset(1, 3), low_limit)} ...
    %       }, ...
    %     'HorizontalAlignment', 'right', ...
    %     'VerticalAlignment', 'top', ...
    %     'BackgroundColor', [.9 .9 .9], ...
    %     'FontSize', fontsize)

    % % *** Lower limit
    % text( 0.99*xL(2), 0.99*yL(2), ...
    %     sprintf('%.2f', maplimits(1)), ...
    %     'HorizontalAlignment', 'right', ...
    %     'VerticalAlignment', 'Bottom', ...
    %     'color', current_colorset(1, :), ...
    %     'BackgroundColor', 'none', ...
    %     'FontSize', fontsize)

    % % *** Upper limit number
    % annotation(...
    %     'textbox', [ax(1)+axis_width ax(2)+axis_height box_width box_height], ...
    %     'String', sprintf('%.2f', maplimits(2)), ...
    %     'LineStyle', 'none', ...
    %     'FontSize', fontsize, ...
    %     'color', current_colorset(end, :), ...
    %     'HorizontalAlignment', 'right', ...
    %     'VerticalAlignment', 'middle', ...
    %     'BackgroundColor', [.9 .9 .9]);        
    % 
    % % *** Lower limit number
    % annotation(...
    %     'textbox', [.67 .80 box_width box_height], ...
    %     'String', sprintf('%.2f', maplimits(1)), ...
    %     'LineStyle', 'none', ...
    %     'FontSize', fontsize, ...
    %     'color', current_colorset(1, :), ...
    %     'HorizontalAlignment', 'right', ...
    %     'VerticalAlignment', 'middle', ...
    %     'BackgroundColor', [.9 .9 .9]);  
end